### ISSUE TITLE
Rust development preparation

### ISSUE THREAD

**Issue by fs-yuta-nakamura** [bonyuta0204/dotfiles#57]
## TODO
- [ ] Quick run for rust file
- [ ] Run test for current file
- [ ] Run fomatter on save
